name = "todoist-mcp-server"
main = "src/index.ts"

compatibility_date = "2024-11-05"
compatibility_flags = ["nodejs_compat"]

# Enable workers.dev subdomain
workers_dev = true

# D1 Database binding for token storage
[[d1_databases]]
binding = "DB"
database_name = "todoist-mcp-db"
database_id = "04870dd1-25c7-42f5-ab30-5f97b920ced2"

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "TodoistMCP"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TodoistMCP"]